from fastapi.testclient import TestClient
import pytest

from app.main import app
import app.services.gemini_service as gemini_service


class DummyService:
    def generate(self, prompt: str, **kwargs) -> str:
        if "quiz generator" in prompt.lower():
            return "1. What is 2+2?\nA. 3\nB. 4\nC. 5\nD. 6\nAnswer: B\nExplanation: 2+2=4"
        return "# Result\nA generated learning response."


class FallbackService:
    def generate(self, prompt: str, **kwargs) -> str:
        return "# Local response\nGenerated by LaMini."


def test_health_check():
    client = TestClient(app)
    response = client.get('/health')

    assert response.status_code == 200
    assert response.json() == {
        'status': 'ok',
        'message': 'EduGenie is healthy and ready to serve requests.',
    }


@pytest.mark.parametrize(
    ("path", "payload"),
    [
        ("/qa/", {"question": "What is photosynthesis?"}),
        ("/explain/", {"topic": "Photosynthesis", "level": "beginner"}),
        ("/quiz/", {"topic": "Basic math", "num_questions": 3}),
        ("/summarize/", {"text": "A short passage to summarize."}),
        ("/roadmap/", {"subject": "Python", "duration_weeks": 2}),
    ],
)
def test_feature_routes_return_valid_json(monkeypatch, path, payload):
    monkeypatch.setattr(gemini_service, "_service_instance", DummyService())
    response = TestClient(app).post(path, json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["success"] is True
    assert body["markdown"]


def test_homepage_loads():
    response = TestClient(app).get("/")

    assert response.status_code == 200
    assert 'id="dashboard-root"' in response.text


def test_gemini_failure_uses_local_fallback(monkeypatch):
    monkeypatch.setattr(gemini_service, "get_lamini_service", lambda: FallbackService())
    service = gemini_service.GeminiService(api_key="test-key")

    class FailingModels:
        @staticmethod
        def generate_content(**kwargs):
            raise RuntimeError("429 RESOURCE_EXHAUSTED")

    class FailingClient:
        models = FailingModels()

    service.client = FailingClient()

    assert service.generate("Explain gravity") == "# Local response\nGenerated by LaMini."


def test_missing_gemini_key_uses_local_fallback(monkeypatch):
    monkeypatch.setattr(gemini_service, "get_lamini_service", lambda: FallbackService())

    assert gemini_service.GeminiService(api_key="").generate("Explain gravity") == "# Local response\nGenerated by LaMini."
